jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Test PowerShell
        run: echo "Hello from my Windows PC"

  deploy:
    needs: test
    runs-on: self-hosted

    steps:
      - name: Deploy
        run: echo "Deploying from my Windows PC"