name: CI Pipeline Demo

on:
  push:
    branches: ["main"]

jobs:

  build-job:
    runs-on: self-hosted

    steps:
      - name: Checkout code        # download the source code of the repository
        uses: actions/checkout@v4  #action that checks out your repository so your workflow can access it

      - name: Setup Node.js        # setup Node.js environment
        uses: actions/setup-node@v4 #action that sets up the Node.js environment
        with:                     # specify the Node.js version and cache settings
          node-version: 20
          cache: npm              # enable caching for npm dependencies 

      - name: Install dependencies  # install project dependencies using npm
        shell: cmd                  # specify the shell to use
        run: npm ci                 # run npm install command clean install mode

      - name: Build project
        shell: cmd                 
        run: npm run build       # run the build script defined in package.json to compile the project

      - name: Move node_modules to dist  # move the node_modules directory to the dist folder to include dependencies in the build artifacts
        shell: cmd
        run: move node_modules dist       # move node_modules directory to dist folder

      - name: Copy package.json         
        shell: cmd
        run: copy package.json dist\

      - name: Upload build artifacts  # upload the build artifacts to GitHub Actions for later use
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: dist


  test-job: # job to run tests
    runs-on: self-hosted
    needs: build-job # depend on the build job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        shell: cmd
        run: npm ci

      - name: Run tests
        shell: cmd
        run: npm test

      - name: Upload test coverage  # upload the test coverage report to GitHub Actions for later use
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage
          path: coverage
  lint:
  runs-on: self-hosted
  needs: build-job

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      shell: cmd
      run: npm ci

    - name: Run linting
      shell: cmd
      run: npm run lint -- --format json --output-file eslint-report.json

    - name: Upload linting report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lint-report
        path: eslint-report.json