name: CI Pipeline Demo
on:
  push: # Trigger the workflow on push events to the main branch if you wont to "trigger mannually you can use workflow_dispatch"
    branches: ["main"]

jobs:

  # =========================
  # BUILD JOB
  # =========================
  build-job:
    runs-on: self-hosted

    steps:
      - name: Checkout code #this step checks out the repository so that the workflow can access its contents
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        shell: cmd
        run: npm ci

      - name: Build project
        shell: cmd
        run: npm run build

      - name: Move node_modules to dist
        shell: cmd
        run: move node_modules dist

      - name: Copy package.json
        shell: cmd
        run: copy package.json dist\

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: dist


  # =========================
  # TEST JOB
  # =========================
  test-job:
    runs-on: self-hosted
    needs: build-job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        shell: cmd
        run: npm ci

      - name: Run tests
        shell: cmd
        run: npm test

      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage
          path: coverage


  # =========================
  # LINT JOB
  # =========================
  lint:
    runs-on: self-hosted
    needs: build-job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        shell: cmd
        run: npm ci

      - name: Run linting
        shell: cmd
        run: npm run lint:report
        # This command generates the linting report in JSON format

      - name: Upload linting report
        uses: actions/upload-artifact@v4
        if: always()
        # Upload the report regardless of the linting result
        with:
          name: lint-report
          path: eslint-report.json


  # =========================
  # DEPLOY JOB
  # =========================
  deploy:
    runs-on: self-hosted
    needs: [build-job, test-job, lint]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        shell: cmd
        run: npm ci

      - name: Deploy application
        shell: cmd
        run: echo Deploying application.. good luck!